#!/bin/sh

branch=$(git branch --show-current)

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
	echo "🚨🚨 You can not commit to the master branch. Please switch to the dev branch."
	exit 1
fi