#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo "Running prepare-commit-msg hook"

# get the current branch name
BRANCH_NAME=$(git branch --show-current)

# return if not in dev branch
if [ "$BRANCH_NAME" != "dev" ]; then
    exit 0
fi

# read the content of the README.md file
PHIL_PROJECT_FILE=$(cat .phil-project)

# get the version of the project
VERSION=$(echo $PHIL_PROJECT_FILE | grep -oP 'version:\K[0-9]+\.[0-9]+\.[0-9]+')

echo "v$VERSION - $(cat $COMMIT_MSG_FILE)" > $COMMIT_MSG_FILE

echo "$(cat $COMMIT_MSG_FILE)"

echo "prepare-commit-msg hook finished"