#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo "Running prepare-commit-msg hook"

# get the current branch name
BRANCH_NAME=$(git branch --show-current)

# return if not in dev branch
if [ "$BRANCH_NAME" != "dev" ]; then
    exit 0
fi

# read the content of the README.md file
PHIL_PROJECT_FILE=$(cat .phil-project)

# get the version of the project
VERSION=$(echo $PHIL_PROJECT_FILE | grep -oP 'version:\K[0-9]+\.[0-9]+\.[0-9]+')

# get the branch name and split it by '-' and get the first element
issue_id=$(echo $BRANCH_NAME | cut -d'-' -f1)

if [ ! -z "$issue_id" ]; then
    echo "Found Issue ID: $issue_id"
    issue_id="[$issue_id] "
else
    issue_id=""
fi

echo "$issue_idv$VERSION - $(cat $COMMIT_MSG_FILE)" > $COMMIT_MSG_FILE

echo "prepare-commit-msg hook finished"
exit 1