#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo "Running prepare-commit-msg hook"

# get the current branch name
BRANCH_NAME=$(git branch --show-current)

# read the content of the README.md file
PHIL_PROJECT_FILE=$(cat .phil-project)

# get the version of the project
VERSION=$(echo $PHIL_PROJECT_FILE | grep -oP 'version:\K[0-9]+\.[0-9]+\.[0-9]+')

# get the branch name and split it by '-' and get the first element
issue_id=$(echo $BRANCH_NAME | cut -d'-' -f1)

if [[ $issue_id =~ ^[0-9]+$ ]]; then
    echo "Found Issue ID: $issue_id"
    issue_id="- [#$issue_id] $VERSION"
else
    issue_id="- $VERSION"
fi

echo "$(cat $COMMIT_MSG_FILE) $issue_id" > $COMMIT_MSG_FILE

echo "Updated commit message: $(cat $COMMIT_MSG_FILE)"

echo "prepare-commit-msg hook finished"