#!/bin/bash

##########################
### templify installer ###
##########################

yesFlag=false
version="latest"
homePath=$HOME/.templify

while getopts "yvp:" opt; do
  case $opt in
    y)
      yesFlag=true
      ;;
    v)
      version=$OPTARG
      ;;
    p)
      homePath=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

echo "Installing templify..."
echo "This will install a binary to $homePath and add it to your PATH."
if [ "$yesFlag" = false ]; then
  read -p "Are you sure you want to continue? (y/N) " response < /dev/tty
  if [[ ! "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
      # echo in line with the prompt
      echo "No"
      echo "Aborting."
      exit 1
  fi
fi
echo "Yes"
# print to the console in same line
echo "Installing..."

# get version
if [ "$version" = "latest" ]; then
  echo "Looking for the latest release..."
  ## Get meta data from the latest release
  json=$(curl -s https://api.github.com/repos/cophilot/templify/releases/latest)

  # get the tag name of the latest release
  version=$(echo $json | grep -Po '"tag_name": "\K.*?(?=")')
  echo "Found version: $version"
else
  echo "Looking for the release with the tag $version..."
  #check if the tag exists
  json=$(curl -s https://api.github.com/repos/cophilot/templify/releases/tags/$version)
  msg=$(echo $json | grep -Po '"message": "\K.*?(?=")')
  if [ "$msg" = "Not Found" ]; then
    echo "Error: No release found with the tag $version"
    exit 1
  fi
fi

url=https://github.com/cophilot/templify/releases/download/$version/tpy

echo "Creating installation directory $homePath..."
mkdir -p $homePath/bin

# remove any existing binary
echo "Removing existing binary..."
rm -f $homePath/bin/tpy

# download the binary and save as an executable
echo "Downloading binary from $url ..."
curl -L $url -o $homePath/bin/tpy

# check if the download was successful
if [ $? -ne 0 ]; then
  echo "Download failed! Exiting."
  exit 1
fi

echo "Download successful!"
chmod +x $homePath/bin/tpy

# add the binary to the PATH
echo "Adding $homePath/bin to PATH..."
echo "export PATH=$homePath/bin:\$PATH" >> ~/.bashrc

echo "templify successfully installed to $homePath/bin"
echo "You may need to restart your shell for the changes to take effect"
echo "Run 'tpy help' to get started"

