#!/bin/bash

##########################
### templify installer ###
##########################

yesFlag=false
version="latest"

while getopts "yv:" opt; do
  case $opt in
    y)
      yesFlag=true
      ;;
    v)
      version=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

echo "Installing templify..."
echo "This will install a binary to /usr/local/bin"
if [ "$yesFlag" = false ]; then
  read -p "Are you sure you want to continue? (y/N) " response < /dev/tty
  if [[ ! "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
      echo "No"
      echo "Aborting."
      exit 1
  fi
fi
echo "Yes"

if [ "$version" = "latest" ]; then
  echo "Looking for the latest release..."
  ## Get meta data from the latest release
  json=$(curl -s https://api.github.com/repos/cophilot/templify/releases/latest)

  # get the tag name of the latest release
  version=$(echo $json | grep -Po '"tag_name": "\K.*?(?=")')
  echo "Found version: $version"
else
  echo "Looking for the release with the tag $version..."
  #check if the tag exists
  json=$(curl -s https://api.github.com/repos/cophilot/templify/releases/tags/$version)
  msg=$(echo $json | grep -Po '"message": "\K.*?(?=")')
  if [ "$msg" = "Not Found" ]; then
    echo "Error: No release found with the tag $version"
    exit 1
  fi
fi


url=https://github.com/cophilot/templify/releases/download/$version/tpy

# download the binary and save as an executable
rm -f /usr/local/bin/tpy

echo "Downloading binary from $url ..."
curl -L $url -o /usr/local/bin/tpy

# check if the download was successful
if [ $? -ne 0 ]; then
  echo "Download failed! Exiting."
  exit 1
fi
chmod +x /usr/local/bin/tpy

echo "templify successfully installed to /usr/local/bin/tpy"
echo "Run 'tpy help' to get started"

