#!/bin/bash

# Install rust
if ! command -v rustup &> /dev/null
then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    # Install cargo
    source $HOME/.cargo/env
fi

# Install rustfmt
rustup component add rustfmt

# Install clippy
rustup component add clippy

# Install specific rust version
rustup install 1.82.0
rustup default 1.82.0


# Set git hooks
git config --local core.hooksPath .githooks/

git pull
git checkout dev
git pull

# run to install dependencies
cargo run