pub fn get_readme_content() -> String {
    let content = "# Welcome to templify!

This is a README file generated by templify.

## What is templify?

templify is a command line tool that helps you manage your project templates.

## How to use templify?

Run `templify init` to initialize Templify in your project.

by Philipp B.
";

    return content.to_string();
}
