/// Get the content for a new templify file
pub fn templify_file_blank(name: String, description: String, path: String) -> String {
    let content = format!("# This is the '{}' template
# This file is used by templify to generate new files from this template.
# You can use the following variables in this file:

# description: The description of the template 
# path: The path where the file should be generated based on the project root (you can also use placeholders here)
# vars: # Define a variable placeholders that can be used in the file content
#    - package # Variable Placeholder
#    - subdir(src) # Variable Placeholder with default value
#    - project[frontend,backend] # Variable Placeholder with list of values

# IMPORTANT: Lines starting with a . are auto generated and should not be changed.

description: {}
path: {}
", name, description, path);

    content.to_string()
}

/// Get the content for the init README file
pub fn get_init_readme_content() -> String {
    let content = format!("<img src=\"https://raw.githubusercontent.com/cophilot/templify/master/assets/logo.png\" alt=\"\" width=\"30%\"/>
    
# Welcome to templify (v{})

_This is a README file generated by templify._

---

## What is templify?

templify is a command line tool that helps you manage your project templates.

---

To learn more about templify, please visit [templify.philipp-bonin.com](https://templify.philipp-bonin.com/).

---

## How to use templify?

When you can see this file, you have already initialized templify in this project. You can now create your own templates and generate new files from them.

### Create a new template

To create a new template, you can use the following command:

```bash
tpy new <template-name>
```

This will create a new folder in the `.templates` folder with the given name. You can now add files to this folder that will be used to generate new files from this template.
Inside the folder you will also find a `.templify.yml` file. This file is used by templify to generate new files from this template. Please open and read the file to learn more about how to use it.

### Load templates 

You can also load templates from a GitHub repository into your project:

```bash
tpy load <url>
```

The url should point to a folder inside a GitHub repository. Each folder inside there will be imported as a template in your _.templates_. See the [templify-vault](https://github.com/cophilot/templify?tab=readme-ov-file#templify-vault) for more informations.

### List all templates

To list all templates, you can use the following command:

```bash
tpy list
```

### Generate a new file from a template

To generate a new file from a template, you can use the following command:

```bash
tpy generate <template-name> <given-name>
```

This will create a new file from the given template in the current project folder with the given name.

---

## Placeholders

- `$$name$$`: The name of the new file (This placeholder supports case conversion).
- `$$year$$`: The current year.
- `$$month$$`: The current month as a number.
- `$$month-name$$`: The current month as a name.
- `$$day$$`: The current day.
- `$$git-name$$`: The name of the git user.

### Case conversion

Case conversion is used to convert placeholders to different case styles. You can use them by adding a `.` and the case style to a placeholder that supports case conversion.

_Example: `$$name.kebab$$`_

You can use the following case conversion:

- `$$<placeholder>.lower$$`: Lower case (e.g. `mycomponent`)
- `$$<placeholder>.upper$$`: Upper case (e.g. `MYCOMPONENT`)
- `$$<placeholder>.camel$$`: Camel case (e.g. `myComponent`)
- `$$<placeholder>.snake$$`: Snake case (e.g. `my_component`)
- `$$<placeholder>.kebab$$`: Kebab case (e.g. `my-component`)
- `$$<placeholder>.pascal$$`: Pascal case (e.g. `MyComponent`)
- `$$<placeholder>.macro$$`: Macro case (e.g. `MY_COMPONENT`)
- `$$<placeholder>.train$$`: Train case (e.g. `My-Component`)

---

by [Philipp B.](https://github.com/cophilot)
", env!("CARGO_PKG_VERSION"));

    content.to_string()
}
